//! Attachments, voice notes and thumbnails.
//!
//! * The source is read through a file descriptor path (`/proc/self/fd/N` on Android) so no plaintext copy is ever written.
//! * Only CIPHERTEXT is written to disk (a temp file under `tmp/`, deleted immediately and swept on lock/background/start).
//! * Each attachment (and each thumbnail) gets a fresh random key; sizes are Padmé-padded; the descriptor (key, name, type) travels only
//!   inside the E2EE message and the vault.
//! * Thumbnails are generated by the app locally and encrypted exactly like the file: the relay never sees or creates plaintext previews.
use super::engine::*;
use super::engine_msg::msg_key_for;
use super::model::*;
use crate::attachment::{decrypt_stream, encrypt_attachment, encrypt_stream, AttachmentDescriptor};
use crate::error::{Result, SecurityError};
use cipher_wire::Id16;
use std::path::{Path, PathBuf};
use zeroize::Zeroizing;

pub const MAX_THUMB_BYTES: usize = 128 * 1024;

/// Deletes the ciphertext temp file when dropped, success or failure.
struct TempFile(PathBuf);
impl Drop for TempFile {
    fn drop(&mut self) {
        let _ = std::fs::remove_file(&self.0);
    }
}

fn fresh(dir: &Path, ext: &str) -> Result<TempFile> {
    std::fs::create_dir_all(dir).map_err(|_| SecurityError::Attachment("temp dir"))?;
    let name = Id16(crate::rng::array::<16>()?).to_hex();
    Ok(TempFile(dir.join(format!("{name}.{ext}"))))
}

impl Engine {
    #[allow(clippy::too_many_arguments)]
    pub fn send_attachment(
        &mut self,
        conv: &Id16,
        src_path: &str,
        mime: &str,
        filename: &str,
        kind: AttachmentKind,
        caption: &str,
        thumbnail_jpeg: Option<&[u8]>,
        duration_ms: Option<u32>,
        reply_to: Option<Id16>,
        progress: &mut dyn FnMut(u64, u64) -> bool,
    ) -> Result<StoredMessage> {
        let total = std::fs::metadata(src_path).map(|m| m.len()).unwrap_or(0);
        let src = std::fs::File::open(src_path).map_err(|_| SecurityError::Attachment("cannot open source"))?;
        self.send_attachment_reader(
            conv,
            std::io::BufReader::new(src),
            total,
            mime,
            filename,
            kind,
            caption,
            thumbnail_jpeg,
            duration_ms,
            reply_to,
            progress,
        )
    }

    /// Same as `send_attachment` for an in-memory source (voice notes: the recording never exists as a plaintext file).
    #[allow(clippy::too_many_arguments)]
    pub fn send_attachment_bytes(
        &mut self,
        conv: &Id16,
        data: &[u8],
        mime: &str,
        filename: &str,
        kind: AttachmentKind,
        duration_ms: Option<u32>,
        reply_to: Option<Id16>,
        progress: &mut dyn FnMut(u64, u64) -> bool,
    ) -> Result<StoredMessage> {
        if data.len() > 16 * 1024 * 1024 {
            return Err(SecurityError::Attachment("in-memory source too large"));
        }
        self.send_attachment_reader(
            conv,
            std::io::Cursor::new(data),
            data.len() as u64,
            mime,
            filename,
            kind,
            "",
            None,
            duration_ms,
            reply_to,
            progress,
        )
    }

    #[allow(clippy::too_many_arguments)]
    fn send_attachment_reader<R: std::io::Read>(
        &mut self,
        conv: &Id16,
        src: R,
        total: u64,
        mime: &str,
        filename: &str,
        kind: AttachmentKind,
        caption: &str,
        thumbnail_jpeg: Option<&[u8]>,
        duration_ms: Option<u32>,
        reply_to: Option<Id16>,
        progress: &mut dyn FnMut(u64, u64) -> bool,
    ) -> Result<StoredMessage> {
        self.guard()?;
        if self.conversation(conv)?.state != ConvState::Active {
            return Err(SecurityError::Denied("conversation is not active"));
        }
        if caption.chars().count() > 1000 || (kind == AttachmentKind::Voice && mime != "audio/aac") {
            return Err(SecurityError::Malformed("attachment parameters"));
        }
        let tmp = fresh(&self.temp_dir("up"), "enc")?;
        let out = std::fs::File::create(&tmp.0).map_err(|_| SecurityError::Attachment("cannot create temp file"))?;
        let mut high = 0u64; // progress must never go backwards (padding bytes count as work done)
        let desc = encrypt_stream(src, std::io::BufWriter::new(out), mime, filename, true, &mut |done| {
            high = high.max(done);
            progress(high, total.max(high))
        })?;
        let path = tmp.0.to_str().ok_or(SecurityError::Attachment("temp path"))?.to_owned();
        let blob_id = self.api()?.upload_blob_file(&path)?;
        drop(tmp); // ciphertext temp file removed right after upload

        let (thumb_blob_id, thumb_descriptor) = match thumbnail_jpeg {
            Some(t) if !t.is_empty() => {
                if t.len() > MAX_THUMB_BYTES {
                    return Err(SecurityError::Attachment("thumbnail too large"));
                }
                let (ct, d) = encrypt_attachment(t, "image/jpeg", "thumb.jpg")?;
                let id = self.api()?.upload_blob(ct)?;
                (Some(id), Some(String::from_utf8(d.to_bytes()?.to_vec()).map_err(|_| SecurityError::Attachment("descriptor"))?))
            }
            _ => (None, None),
        };
        let att = AttachmentRef {
            kind,
            blob_id,
            descriptor: String::from_utf8(desc.to_bytes()?.to_vec()).map_err(|_| SecurityError::Attachment("descriptor"))?,
            thumb_blob_id,
            thumb_descriptor,
            duration_ms,
        };
        let frame = Frame {
            v: 1,
            id: Id16(crate::rng::array::<16>()?),
            ts_ms: self.now_ms(),
            reply_to,
            content: Content::Attachment { caption: caption.to_owned(), att },
        };
        let m = self.queue_app_message(conv, frame, true, false)?.ok_or(SecurityError::InvalidState)?;
        progress(high.max(total), high.max(total));
        self.flush_if_immediate();
        Ok(self.message(conv, &m.id)?.unwrap_or(m))
    }

    /// Download + verify + decrypt an attachment (or its thumbnail) into memory. Fails closed on ANY integrity problem and never
    /// returns partial plaintext. No plaintext is cached or written to disk by the engine.
    pub fn open_attachment(
        &mut self,
        conv: &Id16,
        msg: &Id16,
        thumbnail: bool,
        progress: &mut dyn FnMut(u64, u64) -> bool,
    ) -> Result<Zeroizing<Vec<u8>>> {
        self.guard()?;
        let m = self
            .vault
            .with_store(|s| match msg_key_for(s, conv, msg)? {
                Some(k) => super::engine_msg::get_message_rec(s, &format!("m:{}", conv.to_hex()), &k),
                None => Ok(None),
            })?
            .ok_or(SecurityError::NotFound("message"))?;
        if m.unavailable {
            return Err(SecurityError::Denied("message unavailable: group access revoked"));
        }
        let Content::Attachment { att, .. } = m.content else { return Err(SecurityError::Malformed("not an attachment")) };
        let (blob, desc_json) = if thumbnail {
            (
                att.thumb_blob_id.ok_or(SecurityError::NotFound("thumbnail"))?,
                att.thumb_descriptor.ok_or(SecurityError::NotFound("thumbnail"))?,
            )
        } else {
            (att.blob_id, att.descriptor)
        };
        let desc = AttachmentDescriptor::from_bytes(desc_json.as_bytes())?;
        let tmp = fresh(&self.temp_dir("down"), "enc")?;
        let path = tmp.0.to_str().ok_or(SecurityError::Attachment("temp path"))?.to_owned();
        self.api()?.download_blob_file(&blob, &path, desc.ciphertext_len)?;
        let f = std::fs::File::open(&tmp.0).map_err(|_| SecurityError::Attachment("cannot read download"))?;
        let total = desc.plaintext_len;
        decrypt_stream(std::io::BufReader::new(f), &desc, &mut |done| progress(done, total))
    }
}
