#!/usr/bin/env python3
"""Generate docs/SECURITY_INVARIANTS.md from security/invariants.json.

Usage: gen_invariants_doc.py [--check]   (--check fails if the committed doc is stale)
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
data = json.loads((ROOT / "security/invariants.json").read_text())

out = []
out.append("# Security invariants\n")
out.append("<!-- GENERATED by scripts/gen_invariants_doc.py from security/invariants.json. Do not edit by hand. -->\n")
out.append(
    "Each invariant is a testable statement tied to the threat model (`THREAT_MODEL.md`). "
    "`security/invariants.json` is the source of truth; `scripts/check_invariants.py` fails CI if a mapped test "
    "disappears, and the full test suite fails CI if any mapped test fails.\n"
)
out.append("**Status meanings.** `automated`: exercised by tests at the stated scope. `partial`: tested at the stated scope, "
           "with the gap listed. `manual`: cannot be automated here.\n")
out.append("| ID | Invariant | Status | Tests |")
out.append("| --- | --- | --- | --- |")
for i in data["invariants"]:
    out.append(f"| {i['id']} | {i['statement']} | {i['status']} | {len(i['tests'])} |")
out.append("")
for i in data["invariants"]:
    out.append(f"## {i['id']} — {i['statement']}\n")
    out.append(f"* **Status:** {i['status']}")
    out.append(f"* **Threats (docs/THREAT_MODEL.md):** {', '.join(i.get('threats', [])) or 'n/a'}")
    out.append(f"* **Scope tested:** {i['scope']}")
    out.append(f"* **Known gap:** {i['gap']}")
    out.append("* **Tests:**")
    for t in i["tests"]:
        if t["kind"] == "rust":
            out.append(f"  * `{t['name']}` (Rust)")
        elif t["kind"] == "kotlin":
            out.append(f"  * `{t['name']}` (Kotlin, `{t['file']}`)")
        else:
            out.append(f"  * `{t['name']}` (script)")
    out.append("")
text = "\n".join(out)
target = ROOT / "docs/SECURITY_INVARIANTS.md"
if "--check" in sys.argv:
    if not target.exists() or target.read_text() != text:
        print("docs/SECURITY_INVARIANTS.md is stale: run scripts/gen_invariants_doc.py")
        sys.exit(1)
    print("ok: docs/SECURITY_INVARIANTS.md is up to date")
else:
    target.write_text(text)
    print("wrote", target)
